version: "3.2"
services:
  http:
    image: gphalippou/weflat:http_latest
    hostname: apache
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    depends_on:
      - client
    volumes:
      - type: volume
        source: vfrontend
        target: /var/www/html
        volume:
          nocopy: true
    restart: always

  client:
    image: gphalippou/weflat:frontend_latest
    hostname: client
    networks:
      - backend
    depends_on:
      - server
    volumes:
      - vfrontend:/app/browser
      - /srv/weflat/frontend/log:/app/log
    restart: always

  server:
    image: gphalippou/weflat:backend_latest
    hostname: server
    volumes:
      - /srv/weflat/backend/log:/app/log
      - /srv/weflat/backend/conf:/app/config
    networks:
      - backend
    depends_on:
      - database
    restart: always

  database:
    image: gphalippou/weflat:database_latest
    hostname: database
    environment:
     PGUSER: sa
     PGPORT: 5432
     PGPASSWORD: weflat123$$
     PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/pgsql9/data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

networks:
    frontend:
    backend:

volumes:
  vfrontend:
  