apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: http
  name: http
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    protocol: TCP
  selector:
    io.kompose.service: http
status:
  loadBalancer: {}
