version: 2
jobs:
  build:
    steps:
      - checkout
      - run: docker-compose --project-name weflat build
  deploy:
    steps:
      - checkout
      - run: docker-compose --project-name weflat up -d
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy