version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true    # default - false
      
    branches:
        only:
          - docker
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: |
          docker build -t http_latest http
          docker build -t frontend_latest frontend
          docker build -t backend_latest backend
          docker build -t database_latest database
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push gphalippou/weflat:http_latest
          docker push gphalippou/weflat:frontend_latest
          docker push gphalippou/weflat:backend_latest
          docker push gphalippou/weflat:database_latest