version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image:latest
      
    branches:
        only:
          - docker
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true
      - run: |
          docker build -t http:latest http
          docker build -t frontend:latest frontend
          docker build -t backend:latest backend
          docker build -t database:latest database
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push http
          docker push frontend
          docker push backend
          docker push database