version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true    # default - false
      
    branches:
        only:
          - docker
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: |
          docker build -t http:latest http
          docker build -t frontend:latest frontend
          docker build -t backend:latest backend
          docker build -t database:latest database
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push gphalippou/weflat:http:latest
          docker push gphalippou/weflat:frontend:latest
          docker push gphalippou/weflat:backend:latest
          docker push gphalippou/weflat:database:latest