version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: false
      
    branches:
        only:
          - test
          - master
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: |
          export ANGULAR_ENVIRONMENT=`eval "echo $"${CIRCLE_BRANCH^^}"_ANGULAR_ENVIRONMENT"`
          export MAVEN_PROFILE=`eval "echo $"${CIRCLE_BRANCH^^}"_MAVEN_PROFILE"`
          export TAG_NAME=`eval "echo $"${CIRCLE_BRANCH^^}"_TAG_NAME"`
          export WEB_HOOK=`eval "echo $"${CIRCLE_BRANCH^^}"_WEB_HOOK"`
          docker build -t gphalippou/weflat:http_${TAG_NAME}_latest http
          docker build -t gphalippou/weflat:frontend_${TAG_NAME}_latest --build-arg environment=$ANGULAR_ENVIRONMENT frontend
          docker build -t gphalippou/weflat:backend_${TAG_NAME}_latest --build-arg profile=$MAVEN_PROFILE backend
          docker build -t gphalippou/weflat:database_${TAG_NAME}_latest database
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push gphalippou/weflat:http_${TAG_NAME}_latest
          docker push gphalippou/weflat:frontend_${TAG_NAME}_latest
          docker push gphalippou/weflat:backend_${TAG_NAME}_latest
          docker push gphalippou/weflat:database_${TAG_NAME}_latest
          if ! [[ -z "${WEB_HOOK}" ]]; then
            curl -X GET $WEB_HOOK
          fi
