version: 2
jobs:
  build:
    docker:
      - image: circleci/buil-image:latest
      
    branches:
        only:
          - docker
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: |
          docker build -t http:latest -f http/Dockerfile .
          docker build -t frontend:latest -f frontend/Dockerfile .
          docker build -t backend:latest -f backend/Dockerfile .
          docker build -t database:latest -f database/Dockerfile .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push http
          docker push frontend
          docker push backend
          docker push database