package fr.weflat.backend.enums;

public enum VisitStatusEnum {
	UNASSIGNED,
	WAITING_FOR_PAYMENT,
	BEING_ASSIGNED,
	IN_PROGRESS,
	REPORT_BEING_WRITTEN,
	REPORT_AVAILABLE,
	REFUNDED,
	CANCELED,
	ARCHITECT_PAID
}
