apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
spec:
  rules:
    - host: weflat.westeurope.cloudapp.azure.com
      http:
        paths:
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: server-svc
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-svc
              port:
                number: 80