name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the frontend
      working-directory: frontend
      run: docker build . --file Dockerfile --tag frontend:dev
    - name: Build the backend
      working-directory: backend
      run: docker build . --file Dockerfile --tag backend:dev
