name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  CR_PAT: ${{secrets.TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      run: echo $CR_PAT | docker login ghcr.io -u Guerric-P --password-stdin
    - name: Build the frontend
      working-directory: frontend
      run: docker build . --file Dockerfile --tag ghcr.io/guerric-p/frontend:dev && docker push ghcr.io/guerric-p/weflat-frontend:dev
    - name: Build the backend
      working-directory: backend
      run: docker build . --file Dockerfile --tag ghcr.io/guerric-p/backend:dev && docker push ghcr.io/guerric-p/weflat-backend:dev
